INSERT IGNORE INTO m_permission VALUES ('null', 'service', 'CREATE_HARDWAREPLAN', 'HARDWAREPLAN', 'CREATE', '0');
INSERT IGNORE INTO m_permission VALUES ('null', 'service','CREATE_CREATEHARDWAREDEVICEPLAN','CREATEHARDWAREDEVICEPLAN', 'CREATE', '0');
