package org.mifosplatform.organisation.message.domain;

public class BillingMessageTemplateConstants {
	
	public static final String CONFIG_PROPERTY_MAKER_CHECKER="maker-checker";
	
	public static final String MESSAGE_TEMPLATE_CREATE_SELFCARE="CREATE SELFCARE";
	public static final String MESSAGE_TEMPLATE_SELFCARE_REGISTER="SELFCARE REGISTRATION";
	public static final String MESSAGE_TEMPLATE_NEW_SELFCARE_PASSWORD="NEW SELFCARE PASSWORD";
	public static final String MESSAGE_TEMPLATE_PROVISION_CREDENTIALS="PROVISION CREDENTIALS";
	public static final String MESSAGE_TEMPLATE_TICKET_TEMPLATE="TICKET_TEMPLATE";
	public static final String MESSAGE_TEMPLATE_CREATE_USER="CREATE USER";
	public static final String MESSAGE_TEMPLATE_PAYMENT_RECEIPT = "PAYMENT_RECEIPT";
	public static final String MESSAGE_TEMPLATE_STATEMENT = "STATEMENT_EMAIL";
	public static final String MESSAGE_TEMPLATE_INVOICE = "INVOICE_EMAIL";
	public static final String MESSAGE_TEMPLATE_PAYMENT = "PAYMENT_EMAIL";
	public static final String MESSAGE_TEMPLATE_NOTIFY_TECHNICAL_TEAM = "NOTIFY_TECHNICAL_TEAM";
	public static final String MESSAGE_TEMPLATE_CREATE_LEAD = "CREATE_LEAD";
	public static final String MESSAGE_TEMPLATE_FOLLOWUP_LEAD = "FOLLOWUP_LEAD_MAIL";
	public static final String MESSAGE_TEMPLATE_CREATE_CUSTOMER="Create Customer";
	public static final String MESSAGE_TEMPLATE_Send_OTP="Send_OTP";

	//SMS Configuration constants
	public static final String MESSAGE_TEMPLATE_SMS_CREATE_SELFCARE = "SMS_CREATE_SELFCARE";
	public static final String MESSAGE_TEMPLATE_SMS_NEW_SELFCARE_PASSWORD = "SMS_NEW_SELFCARE_PASSWORD";
	public static final String MESSAGE_TEMPLATE_SMS_PROVISION_CREDENTIALS = "SMS_PROVISION_CREDENTIALS";
	public static final String MESSAGE_TEMPLATE_SMS_CREATE_USER = "SMS_CREATE_USER";
	public static final String MESSAGE_TEMPLATE_SMS_PAYMENT_RECEIPT = "SMS_PAYMENT_RECEIPT";
	public static final String MESSAGE_TEMPLATE_SMS_NEW_CUSTOMER = "SMS_NEW_CUSTOMER";
	public static final String MESSAGE_TEMPLATE_SMS_NOTIFY_ACTIVATION = "SMS_NOTIFY_ACTIVATION";
	public static final String MESSAGE_TEMPLATE_SMS_NOTIFY_DISCONNECTION = "SMS_NOTIFY_DISCONNECTION";
	public static final String MESSAGE_TEMPLATE_SMS_NOTIFY_RECONNECTION = "SMS_NOTIFY_RECONNECTION";
	public static final String MESSAGE_TEMPLATE_SMS_NOTIFY_PAYMENT = "SMS_NOTIFY_PAYMENT";
	public static final String MESSAGE_TEMPLATE_SMS_NOTIFY_CHANGEPLAN = "SMS_NOTIFY_CHANGEPLAN";
	public static final String MESSAGE_TEMPLATE_SMS_NOTIFY_ORDERTERMINATION = "SMS_SERVICE_TERMINATION";
	public static final String MESSAGE_TEMPLATE_SMS_CREATE_LEAD = "SMS_CREATE_LEAD";
	public static final String MESSAGE_TEMPLATE_SMS_FOLLOWUP_LEAD = "SMS_LEAD_FOLLOWUP";
	public static final String MESSAGE_TEMPLATE_SMS_CREATE_CUSTOMER = "SMS CREATE CUSTOMER";
	public static final String MESSAGE_TEMPLATE_SMS_Send_OTP = "SMS_Send_OTP";
	
	
	// Order Notify Events
	public static final String MESSAGE_TEMPLATE_NOTIFY_ACTIVATION = "NOTIFY ACTIVATION";
	public static final String MESSAGE_TEMPLATE_NOTIFY_DISCONNECTION = "NOTIFY DISCONNECTION";
	public static final String MESSAGE_TEMPLATE_NOTIFY_RECONNECTION = "NOTIFY RECONNECTION";
	public static final String MESSAGE_TEMPLATE_NOTIFY_PAYMENT = "NOTIFY PAYMENT";
	public static final String MESSAGE_TEMPLATE_NOTIFY_CHANGEPLAN = "NOTIFY CHANGEPLAN";
	public static final String MESSAGE_TEMPLATE_NOTIFY_ORDERTERMINATION = "NOTIFY ORDER TERMINATION";
	public static final String MESSAGE_TEMPLATE_PENDING_REQUEST = "PENDING_REQUEST";
	public static final String MESSAGE_TEMPLATE_RETRACK_ORDER = "RETRACK_ORDER";
	
	public static final String MESSAGE_TEMPLATE_SERVICE_SUSPEND = "SERVICE_SUSPEND";
	public static final String MESSAGE_TEMPLATE_SERVICE_TERMINATION = "SERVICE_TERMINATION";
	
	public static final String MESSAGE_TEMPLATE_NOTIFY_PAYMENT_ADJ = "NOTIFY PAYMENT ADJUSTMENT";
	public static final String MESSAGE_TEMPLATE_NOTIFY_SMS_PAYMENT_ADJ = "NOTIFY SMS PAYMENT ADJUSTMENT";
	
	public static final String MESSAGE_TEMPLATE_NOTIFY_PAYMENT_REVERSAL = "NOTIFY PAYMENT REVERSAL";
	public static final String MESSAGE_TEMPLATE_NOTIFY_SMS_PAYMENT_REVERSAL = "NOTIFY SMS PAYMENT REVERSAL";
	
	public static final String MESSAGE_TEMPLATE_NOTIFY_TICKET_ESCALATION="NOTIFY_TICKET_ESCALATION";
	
	

	
	//constants
	public static final String MESSAGE_TEMPLATE_STATUS = "N";
	public static final String MESSAGE_TEMPLATE_EMAIL_FROM = "";
	public static final char MESSAGE_TEMPLATE_MESSAGE_TYPE = 'E';
	public static final char MESSAGE_TEMPLATE_SMS_TYPE = 'M';
	public static final String SELFCARE_REGISTRATION_CONSTANT = "11011";

	

}
